---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: polaris-v1-git
  namespace: flux-system
spec:
  interval: 5m0s
  url: https://github.com/aravindh-murugesan/gitops-polaris
  ref:
    branch: main
