apiVersion: v1
kind: Secret
metadata:
  labels:
    kustomize.toolkit.fluxcd.io/name: cert-manager-duckdns
    kustomize.toolkit.fluxcd.io/namespace: flux-system
  managedFields: []
  name: cert-manager-duckdns-token
  namespace: flux-system
stringData:
  token: ENC[AES256_GCM,data:/D/dxikpgjxVO9ZjQP21RYUIbq6XsmfbtoLqG6pkZxqcwF6W,iv:NzmOYe7s9EdQQqX8aeY5dEqPycqFr2QI3QfFTt/yj3g=,tag:+BvoHyjL72n7ByrLkfMJ3A==,type:str]
type: Opaque
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBUUk1OTTlibzM3eVVYN2hM
        M3NHTm0wdVVtS3llRytmaXV1WDRaNXpWWDJnCks3b0haOFhHTlpvTWxUZkU5V3JT
        L1FBbzhPaCt6QUk2UWo4TG1DQmkwRzQKLS0tIElRWjBpekQ3cHVSK3FzVSszK2wx
        TnM2LzlEdUg1OFpjZEIyZUhDR0FBMUkKvxZvCWwe50vH2nZ/DvF92ZmWiTW863Zp
        HCf5lJYYlIAnVhTp13gKJrybZsghg/fUBkezP6rt/V4Xy13HI65v3Q==
        -----END AGE ENCRYPTED FILE-----
      recipient: age17uext3pdpx2930z637ak5c4rccvltmwevy74rqk60dlelff6yu0qsyjy05
  encrypted_regex: ^(data|stringData|stringdata|encpassword)$
  lastmodified: "2026-09-25T07:45:25Z"
  mac: ENC[AES256_GCM,data:IvDN3fAUZDWX73JhwkY/b8ak2qHBUiwgIQMwa3xq2KET8ESJ+kD4G+lNsAgEdl9HiHlT96l0Jhk8/OXy7Fb7gT5r2XSTKEINUnqnDocb8RhY5vHFBhqyRITuMciitM+BdPwzySHsBPk+nZlGzl/8U93owre+cPAK2RY7OewcFDI=,iv:tlhkvNFC3O01As5OO7uOzpXC6xY2Yq2keZQ7Tc8hwII=,tag:x27zOk8k4awskNcMOEiVyg==,type:str]
  version: 3.13.3
