apiVersion: v1
kind: Secret
metadata:
  name: cert-manager-duckdns-token
  namespace: cert-manager
type: Opaque
stringData:
  token: ENC[AES256_GCM,data:4JyJ9ZKkbkOiNpSog9Wf9iBDHf/L3T9mr4+G0ZYKJ2eI2zMr,iv:n23FWVc/9D3PdqyGAgWuZ+CZuRIey/ZkreVt2qYDf8Y=,tag:zW7Q0qiqht9iG7EyYcXsjg==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBRNktpT1dIY2RPUFl4TkdQ
        TFNLVEJRamlWZ3NCM0dIZ0dxN3hrQXRhY3lVCjkyRFJZWU1VM1NleHRuRFF5OFNh
        bVkrelBnNVdjWTV3V1ljenp1QmE4ZmMKLS0tIDZYdGYvc01wbzMrYWx5cE5hYzlL
        Ujl6WTFmbWZydlNUejNjL2gvSFUycWsK5u3JzOsntdVtzXRktAjAG8XOJbPI2Z3Z
        7+HAXW7fE9ANBjpnqczRlN53kcK7pgrkO4LXFWfbP+yP1j+Td56dsQ==
        -----END AGE ENCRYPTED FILE-----
      recipient: age17uext3pdpx2930z637ak5c4rccvltmwevy74rqk60dlelff6yu0qsyjy05
  encrypted_regex: ^(data|stringData|stringdata|encpassword)$
  lastmodified: "2026-09-24T06:15:51Z"
  mac: ENC[AES256_GCM,data:F5kuLfs9nyoG2l/YKhqbfDyVpm6vtrVCjFrYPmFeZTzvAQgqC0l6ZDOxSfw6oYYhLBFr0GVaV5QMvYPP0PyLdr/c/iJW5vWRD1HnMgZSRGzqUC9o3BNi2HEQG3rFTEcIA38YIN5O7ET6vZBBXpDSMbztLHMWqvGdoxUvQzxRrkY=,iv:cEFeCr2ht7o84J62nP/sBUbYE4NuImKf7vbRjSNXV6Q=,tag:wCPtc2yGxbVdw+QWOcfj9g==,type:str]
  version: 3.13.3
